[2023-12-13 17:03:16,878] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_python_weather_v01.fill 2023-12-13T17:03:15.452362+00:00 [queued]>
[2023-12-13 17:03:16,915] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_python_weather_v01.fill 2023-12-13T17:03:15.452362+00:00 [queued]>
[2023-12-13 17:03:16,916] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-12-13 17:03:16,917] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2023-12-13 17:03:16,918] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-12-13 17:03:16,936] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): fill> on 2023-12-13T17:03:15.452362+00:00
[2023-12-13 17:03:16,955] {standard_task_runner.py:52} INFO - Started process 4320 to run task
[2023-12-13 17:03:16,970] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_python_weather_v01', 'fill', '2023-12-13T17:03:15.452362+00:00', '--job-id', '142', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_weather.py', '--cfg-path', '/tmp/tmpef_sqiid', '--error-file', '/tmp/tmph3_25t_s']
[2023-12-13 17:03:16,983] {standard_task_runner.py:77} INFO - Job 142: Subtask fill
[2023-12-13 17:03:17,091] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_with_python_weather_v01.fill 2023-12-13T17:03:15.452362+00:00 [running]> on host 27393a612fb2
[2023-12-13 17:03:17,238] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ggoni
AIRFLOW_CTX_DAG_ID=dag_with_python_weather_v01
AIRFLOW_CTX_TASK_ID=fill
AIRFLOW_CTX_EXECUTION_DATE=2023-12-13T17:03:15.452362+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-13T17:03:15.452362+00:00
[2023-12-13 17:03:18,134] {python.py:118} INFO - Done. Returned value was: None
[2023-12-13 17:03:18,165] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=dag_with_python_weather_v01, task_id=fill, execution_date=20231213T170315, start_date=20231213T170316, end_date=20231213T170318
[2023-12-13 17:03:18,292] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-13 17:03:18,348] {local_task_job.py:146} INFO - Task exited with return code 0
