[2023-12-13 19:04:45,745] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_python_weather_v01.fill 2023-12-13T18:00:00+00:00 [queued]>
[2023-12-13 19:04:45,772] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_python_weather_v01.fill 2023-12-13T18:00:00+00:00 [queued]>
[2023-12-13 19:04:45,773] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-12-13 19:04:45,773] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2023-12-13 19:04:45,774] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-12-13 19:04:45,788] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): fill> on 2023-12-13T18:00:00+00:00
[2023-12-13 19:04:45,793] {standard_task_runner.py:52} INFO - Started process 702 to run task
[2023-12-13 19:04:45,801] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_python_weather_v01', 'fill', '2023-12-13T18:00:00+00:00', '--job-id', '20', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_weather.py', '--cfg-path', '/tmp/tmpuwhcz2vu', '--error-file', '/tmp/tmp3h5u1ajb']
[2023-12-13 19:04:45,808] {standard_task_runner.py:77} INFO - Job 20: Subtask fill
[2023-12-13 19:04:45,901] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_with_python_weather_v01.fill 2023-12-13T18:00:00+00:00 [running]> on host 21326130d467
[2023-12-13 19:04:45,982] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ggoni
AIRFLOW_CTX_DAG_ID=dag_with_python_weather_v01
AIRFLOW_CTX_TASK_ID=fill
AIRFLOW_CTX_EXECUTION_DATE=2023-12-13T18:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-13T18:00:00+00:00
[2023-12-13 19:04:46,303] {python.py:118} INFO - Done. Returned value was: None
[2023-12-13 19:04:46,318] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=dag_with_python_weather_v01, task_id=fill, execution_date=20231213T180000, start_date=20231213T190445, end_date=20231213T190446
[2023-12-13 19:04:46,418] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-13 19:04:46,454] {local_task_job.py:146} INFO - Task exited with return code 0
