[2023-12-13 17:15:43,402] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_python_weather_v01.fill 2023-12-13T17:15:41.670470+00:00 [queued]>
[2023-12-13 17:15:43,436] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_python_weather_v01.fill 2023-12-13T17:15:41.670470+00:00 [queued]>
[2023-12-13 17:15:43,439] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-12-13 17:15:43,440] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2023-12-13 17:15:43,441] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-12-13 17:15:43,456] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): fill> on 2023-12-13T17:15:41.670470+00:00
[2023-12-13 17:15:43,464] {standard_task_runner.py:52} INFO - Started process 7836 to run task
[2023-12-13 17:15:43,468] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_python_weather_v01', 'fill', '2023-12-13T17:15:41.670470+00:00', '--job-id', '143', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_weather.py', '--cfg-path', '/tmp/tmpx75uzewn', '--error-file', '/tmp/tmp_bgardk7']
[2023-12-13 17:15:43,471] {standard_task_runner.py:77} INFO - Job 143: Subtask fill
[2023-12-13 17:15:43,520] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_with_python_weather_v01.fill 2023-12-13T17:15:41.670470+00:00 [running]> on host 27393a612fb2
[2023-12-13 17:15:43,569] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ggoni
AIRFLOW_CTX_DAG_ID=dag_with_python_weather_v01
AIRFLOW_CTX_TASK_ID=fill
AIRFLOW_CTX_EXECUTION_DATE=2023-12-13T17:15:41.670470+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-13T17:15:41.670470+00:00
[2023-12-13 17:15:44,785] {python.py:118} INFO - Done. Returned value was: None
[2023-12-13 17:15:44,805] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=dag_with_python_weather_v01, task_id=fill, execution_date=20231213T171541, start_date=20231213T171543, end_date=20231213T171544
[2023-12-13 17:15:44,836] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-13 17:15:44,864] {local_task_job.py:146} INFO - Task exited with return code 0
